### PR TITLE
Added a few properties, and behaviour tweak on nextPage()

### PR DESCRIPTION
**Pull request by TomThorpe**
I've added a few properties that I found useful for defining pages and behaviour on pages while using your control, `currentViewController:UIViewController` which just returns the current page's view controller (for example if you want to see which page is currently being viewed and tweak behaviour based on it's class), and `numberOfPages` which just returns the total number of pages, good for if you have some behaviour that depends on the page being the last page.

Also I found it useful for the `nextPage` method to call the finished delegate if the current page is already the last page, so you don't have to check this yourself each time - wondering if you agree?

Many thanks for an excellent control!

### CODE REVIEW

**Comment by ariok** [comment]
@TomThorpe Thank you for sharing these great idea! I'm going to release a new version in a couple of weeks and your suggestions will be included for sure!  (...and sorry for the late reply)

**Comment by TomThorpe** [comment]
That's great, thanks! And thanks again for the control, I use it in a few apps. Looking forward to the update!

**Comment by ariok** [comment]
Hi @TomThorpe ! I've merged your commits. Please note that I've excluded the "nextPage calls finished delegate if already on last page" since I prefer not to add that feature into the library now. 
Let me know if it is ok :) and...  it'd be great if you have some spare time to check the new "staticTags" Inspectable property. I've updated the documentation if you are curious about this feature ;)

**Comment by TomThorpe** [comment]
Hi. Thanks for merging! I'll take a look and try and upgrade soon. Static tags sound like a great idea too :-)

**Pull request merged**
