### PR TITLE
Add a scheme for carthage

### PR DESCRIPTION
**Pull request by kokoron**
I made a scheme for carthage. It is because I wanted to use the [carthage](https://github.com/Carthage/Carthage).

Make Cartfile
```
github "kokoron/BWWalkthrough" "e43b377a59112edda07b0ff1e696679be986501b"
```
And run carthage
```bash
$ carthage update
```

### CODE REVIEW

**Comment by danielbmarques** [comment]
+1 for Carthage support.

**Comment by ariok** [comment]
This is no longer compatible with the new project architecture.

**Comment by danielbmarques** [comment]
@ariok What makes this not compatible with the new project architecture? When I have some spare time I'm thinking of working on adding Carthage support to this myself, but I don't get what's wrong with @kokoron's code.

**Comment by ariok** [comment]
@danielbmarques I've completely updated the project structure when I've added the CocoaPods support. @kokoron pull request is no longer compatible with this new structure -> "This branch has conflicts that must be resolved" 

I'm going to include Carthage support in version 2.0.

**Comment by danielbmarques** [comment]
@ariok Ah, I see. Would you be open to a PR if I add a Carthage scheme now, or would ou rather wait for 2.0? I also updated the code to Swift 2.2 here, I could make a PR for that.

**Pull request closed without merging**
