### PR TITLE
Added support for Swift Package Manager

### PR DESCRIPTION
**Pull request by gabrielPeart**
If approved and merged, please do the same: https://github.com/ariok/BWWalkthrough/pull/127 since it enhances the readme file by providing a clear explanation about how to consume the library via Swift Package Manager.

### CODE REVIEW

**Comment by gabrielPeart** [comment]
@ariok any possibility of getting it merged?

**Comment by ariok** [comment]
@gabrielPeart sorry for the late reply. I'll do my best to merge your pull reqs next week.

**Comment by gleb-gusev** [comment]
It would be awesome to merge this PR, was waiting for a long time for the SPM support. Thanks in advance!

**Comment by ariok** [comment]
...sorry for the very late merge!

**Pull request merged**
