### PR TITLE
Proper upgrade to Swift 2.0

### PR DESCRIPTION
**Pull request by wircho**
Upgraded to Swift 2.0

### CODE REVIEW

**Comment by orangecoding** [comment]
Hey. Is there a reason why this isn't merged already?

**Comment by ariok** [comment]
Hi @orangecoding, I'm sorry it is taking so long... I'm really busy with a huge project and I want to try the code before merging.

**Comment by ariok** [comment]
Merged! Thanks @wircho :)

**Comment by wircho** [comment]
@ariok No prob! :)

**Pull request merged**
