### PR TITLE
update ui when view will appear (the first page should have the prevB…

### PR DESCRIPTION
**Pull request by jerrygdm**
button hidden also the first time the walkthrough appears)

### CODE REVIEW

**Comment by ariok** [comment]
I prefer not to merge this commit since this behaviour is strongly connected to the design implemented.

**Comment by jerrygdm** [comment]
In my opinion is a bug fix…If the user start the walkthrough it see the prevButton…if he press it he page scrolls to the second view…in my opinion is not what a user would expect…

You are coherent with this behavior when you scroll to the next and you come back to the first page: you update the ui and the prev button is not displayed.


Let me know…I’m releasing an update of our app with your well done walkthrough :)

Thanks.

**Comment by ariok** [comment]
You are right absolutely right. To be consistent with the behaviour it should never disappear. I reopen and I'll check your request as soon as possible! 
Thank you

**Comment by ariok** [comment]
Sorry if it takes so long to merge this code!

**Pull request merged**
